image:
  file: .gitpod.Dockerfile

tasks:
- name: Start Couchbase
  prebuild:  cd /opt/couchbase/ && ./start-cb.sh
  command: couchbase-cli bucket-create -c localhost:8091 --username Administrator --password password --bucket default --bucket-type couchbase --bucket-ramsize 256

# exposed ports
ports:
- port: 8091
  onOpen: notify
- port: 8092-10000
  onOpen: ignore
- port: 4369
  onOpen: ignore

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot
